# Generated by Django 4.2.20 on 2025-05-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='feeBal',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
