# Generated by Django 4.2.20 on 2025-05-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_feebal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='feeBal',
            field=models.CharField(default='', max_length=30),
        ),
    ]
