# Generated by Django 5.2 on 2025-05-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_student_feebal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='feeBal',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
