# Generated by Django 5.2.1 on 2025-05-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_student_feebal'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='regNo',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
    ]
