# Generated by Django 5.2.1 on 2025-05-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_student_regno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='regNo',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
