# Generated by Django 5.2.1 on 2025-05-10 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_student_regno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='regNo',
            new_name='admNo',
        ),
    ]
