# Generated by Django 5.2.1 on 2025-05-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_admno_student_regno_alter_student_feebal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='regNo',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
